from typing import Protocol

from .entities import Exhibit, TourPath, VisitorProfile
from .value_objects import ExhibitId, ProfileId, TourPathId, UserId


class ExhibitRepository(Protocol):
    async def get_by_id(self, exhibit_id: ExhibitId) -> Exhibit | None: ...

    async def list_all(self, include_inactive: bool = False) -> list[Exhibit]: ...

    async def list_all_active(self) -> list[Exhibit]: ...

    async def list_by_category(self, category: str, include_inactive: bool = False) -> list[Exhibit]: ...

    async def list_by_hall(self, hall: str, include_inactive: bool = False) -> list[Exhibit]: ...

    async def list_with_filters(
        self,
        category: str | None = None,
        hall: str | None = None,
        floor: int | None = None,
    ) -> list[Exhibit]: ...

    async def find_by_interests(self, interests: list[str], limit: int = 10) -> list[Exhibit]: ...

    async def search_by_name(
        self,
        query: str,
        category: str | None = None,
        hall: str | None = None,
        floor: int | None = None,
        skip: int = 0,
        limit: int = 20,
    ) -> list[Exhibit]: ...

    async def get_distinct_categories(self) -> list[str]: ...

    async def get_distinct_halls(self) -> list[str]: ...

    async def save(self, exhibit: Exhibit) -> Exhibit: ...

    async def delete(self, exhibit_id: ExhibitId) -> bool: ...


class TourPathRepository(Protocol):
    async def get_by_id(self, tour_path_id: TourPathId) -> TourPath | None: ...

    async def list_all(self, include_inactive: bool = False) -> list[TourPath]: ...

    async def list_by_theme(self, theme: str, include_inactive: bool = False) -> list[TourPath]: ...

    async def save(self, tour_path: TourPath) -> TourPath: ...

    async def delete(self, tour_path_id: TourPathId) -> bool: ...


class VisitorProfileRepository(Protocol):
    async def get_by_id(self, profile_id: ProfileId) -> VisitorProfile | None: ...

    async def get_by_user_id(self, user_id: UserId) -> VisitorProfile | None: ...

    async def save(self, profile: VisitorProfile) -> VisitorProfile: ...

    async def update(self, profile: VisitorProfile) -> VisitorProfile: ...
