from typing import List, Optional, Protocol

from .entities import Exhibit, TourPath, VisitorProfile
from .value_objects import ExhibitId, ProfileId, TourPathId, UserId


class ExhibitRepository(Protocol):
    async def get_by_id(self, exhibit_id: ExhibitId) -> Optional[Exhibit]: ...

    async def list_all(self, include_inactive: bool = False) -> List[Exhibit]: ...

    async def list_all_active(self) -> List[Exhibit]: ...

    async def list_by_category(self, category: str, include_inactive: bool = False) -> List[Exhibit]: ...

    async def list_by_hall(self, hall: str, include_inactive: bool = False) -> List[Exhibit]: ...

    async def list_with_filters(
        self,
        category: Optional[str] = None,
        hall: Optional[str] = None,
        floor: Optional[int] = None,
    ) -> List[Exhibit]: ...

    async def find_by_interests(self, interests: List[str], limit: int = 10) -> List[Exhibit]: ...

    async def search_by_name(
        self,
        query: str,
        category: Optional[str] = None,
        hall: Optional[str] = None,
        floor: Optional[int] = None,
        skip: int = 0,
        limit: int = 20,
    ) -> List[Exhibit]: ...

    async def get_distinct_categories(self) -> List[str]: ...

    async def get_distinct_halls(self) -> List[str]: ...

    async def save(self, exhibit: Exhibit) -> Exhibit: ...

    async def delete(self, exhibit_id: ExhibitId) -> bool: ...


class TourPathRepository(Protocol):
    async def get_by_id(self, tour_path_id: TourPathId) -> Optional[TourPath]: ...

    async def list_all(self, include_inactive: bool = False) -> List[TourPath]: ...

    async def list_by_theme(self, theme: str, include_inactive: bool = False) -> List[TourPath]: ...

    async def save(self, tour_path: TourPath) -> TourPath: ...

    async def delete(self, tour_path_id: TourPathId) -> bool: ...


class VisitorProfileRepository(Protocol):
    async def get_by_id(self, profile_id: ProfileId) -> Optional[VisitorProfile]: ...

    async def get_by_user_id(self, user_id: UserId) -> Optional[VisitorProfile]: ...

    async def save(self, profile: VisitorProfile) -> VisitorProfile: ...

    async def update(self, profile: VisitorProfile) -> VisitorProfile: ...
